Fix incorrect documentation for url in StringOptionsWithoutImporter
sass/sass pull request #3278
Opened 2022-04-03 18:46 UTC by ntkme

The current documentation for the `url` field in `StringOptionsWithoutImporter` is incorrect that it does not match the behavior defined in [js-api-spec](https://github.com/sass/sass-spec/blob/126d17ff9f77372b6f68cb0d43dd357165519c93/js-api-spec/compile.test.ts#L124-L133) and actual implementation:

``` js
    it('url is used to resolve relative loads', () =>
      sandbox(dir => {
        dir.write({'foo/bar/_other.scss': 'a {b: c}'});

        expect(
          compileString('@use "other";', {
            url: dir.url('foo/bar/style.scss'),
          }).css
        ).toBe('a {\n  b: c;\n}');
      }));
```

- Fixes https://github.com/sass/dart-sass/issues/1657.

2022-04-06 23:01 UTC, nex3 commented
This behavior doesn't match the behavior [specified here](https://github.com/sass/sass/blob/main/spec/spec.md#compiling-a-string). (Specifically, the part that says "If `url` is not null and `importer` is null, set `importer` to a function that always returns null.") However, after talking it over we've decided that the current actual behavior is likely to be more intuitive for users, so we should stick with it and update the documentation.

**tl;dr**: Please update [the "Compiling a String" procedure](https://github.com/sass/sass/blob/main/spec/spec.md#compiling-a-string) to reflect this behavior as well.

2022-04-07 00:38 UTC, nex3 requested changes

2022-04-07 00:38 UTC, nex3 commented on spec/spec.md
> +  * If `url` is not a `file:` URL, set `importer` to be a no-op importer.
Since we haven't defined the term "no-op" importer, it's probably better to continue to spell out "a function that always returns null".

2022-04-07 23:39 UTC, nex3 commented
I'm treating this as a fast-track proposal. Although the *spec change itself* is backwards-incompatible, the new specification wording matches the existing behavior of the reference implementation so this is not considered a backwards-incompatible change. I'll leave this open for two workdays from now in case anyone has any objections to this change.

2022-04-09 01:38 UTC, ntkme commented
List of related PRs to make implementations consistent with the spec update:
- https://github.com/sass/sass-spec/pull/1785
  - Update JS API spec
- https://github.com/sass/dart-sass/pull/1664
  - Fix dart-sass to set NoOpImporter when `url` is provided and is not a file: URL.
- https://github.com/sass/dart-sass-embedded/pull/83
  - Fix dart-sass-embedded to set NoOpImporter when `url` is not a file: URL.
- https://github.com/sass/embedded-host-node/pull/128
  - Fix embedded-host-node to force a FileSystemImporter for legacy API when `filename` is not provided.

@nex3 PTAL. Thanks!

2022-04-12 00:09 UTC, merged