Allow global functions 'invert()', 'grayscale()', 'opacity()', and 'saturate()' to use 'var()'
sass/sass pull request #3528
Opened 2023-04-04 00:17 UTC by Goodwine

When these functions use `var()` they output the native CSS function with the same name and args.
The saturate spec was expanded to match the existing implementation.

See implementation: https://github.com/sass/dart-sass/pull/1926

2023-04-05 23:06 UTC, nex3 requested changes

2023-04-05 23:06 UTC, nex3 commented on spec/built-in-modules/color.md
> +* If `$color` is a number or a [special variable string], and this function is
I think we should do this logic for all special numbers, not _just_ special variable strings.

2023-04-05 23:06 UTC, nex3 commented on spec/built-in-modules/color.md
> +  * If this function is called with a single argument `$amount`:
Currently, the signature for this function requires two arguments. You'll need to add a separate signature that only takes one argument. (See `rgb()` as an example of an overloaded function.)

2023-04-05 23:06 UTC, nex3 commented on spec/built-in-modules/color.md
> +      inclusive range `[0, 100]`.
Leaving this out was intentional—the old behavior is deprecated, and the canonical spec only includes non-deprecated behavior.

2023-04-05 23:06 UTC, nex3 commented on spec/built-in-modules/color.md
> +[special variable string]: ../spec.md#special-variable-string
We generally put reference links after the first reference so they're easier to clean up later on. Also, I think this term is defined in `functions.md`.

2023-04-07 17:53 UTC, Goodwine commented on spec/built-in-modules/color.md
> +  * If this function is called with a single argument `$amount`:
ohh.... I actually wanted to do it that way but I wasn't sure XD

2023-04-07 22:20 UTC, nex3 approved these changes

2023-04-07 22:21 UTC, merged