[Color 4] Draft 1.4 changes for Color Spaces JS API
sass/sass pull request #3723
Opened 2023-10-19 03:04 UTC by jamesnw

2023-10-20 16:42 UTC, jgerigmeyer commented on proposal/color-4-new-spaces-js.d.ts.md
> +  `value` of `options.lightness`, `minimum` of `0`, and `maximum` of `1`.
@jamesnw For HSL, isn't the max lightness `100`?
```suggestion
  `value` of `options.lightness`, `minimum` of `0`, and `maximum` of `100`.
```

2023-10-23 23:23 UTC, nex3 requested changes

2023-10-23 23:23 UTC, nex3 commented on proposal/color-4-new-spaces-js.d.ts.md
> +* If `value` is less than `minimum`, throw an error.
These should be fuzzy comparisons. If the user passes `lightness: 100.000000000001`, that should be treated as `lightness: 100`.

2023-10-24 14:33 UTC, jamesnw commented on proposal/color-4-new-spaces-js.d.ts.md
> +* If `value` is less than `minimum`, throw an error.
Updated in https://github.com/sass/sass/pull/3723/commits/d7bdd2ec33c588d208ea5235a82829f7660f8960

In addition to lightness and alpha, the dart-sass implementation is also throwing out of range errors for-

- `hwb.whiteness`
- `hwb.blackness`
- `hsl.saturation`

Should I add this behavior to the proposal as well?
What are the overarching rules that this should follow? I think it is "If a channel is clamped, throw out of range errors", but to check-

1. Does bounded vs un-bounded make a difference?
2. Does legacy vs non-legacy make a difference?
3. Does legacy with space specified vs legacy without space specified make a difference?

2023-10-24 21:35 UTC, nex3 commented on proposal/color-4-new-spaces-js.d.ts.md
> +* If `value` is less than `minimum`, throw an error.
Don't treat the Dart Sass implementation as authoritative—it's lagging behind the spec in a few crucial ways. Currently, the _only_ clamped channels are `lightness` and `alpha`, and so those should be the only ones that throw out-of-range errors (although that may change as the result of https://github.com/w3c/csswg-drafts/issues/9484).

2023-10-28 00:00 UTC, nex3 approved these changes

2023-10-28 00:00 UTC, merged