Integrate the deprecations API into the spec/docs/protocol
sass/sass pull request #3826
Opened 2024-04-01 18:34 UTC by jathak

In the process of implementing this, I made two minor changes to the embedded protocol part of the proposal: (1) updating the field IDs since a new field got added to `CompileRequest` since the proposal was written and (2) adding a `deprecation_type` field to `LogEvent` so that the embedded host can pass that information to the JS API. Let me know if these changes are fine to just do here, or if I should factor them out into a separate PR.

[skip dart-sass]
[skip sass-embedded]

2024-04-02 20:24 UTC, nex3 requested changes

2024-04-02 20:24 UTC, nex3 commented on js-api-doc/deprecations.d.ts
> +  'user-authored': Deprecation<'user-authored', 'user'>;
Do we have any testing in place that will catch if we add a deprecation to Dart Sass's enum that isn't listed here? If not, we should—I'm confident I'll make that mistake in the future :sweat_smile:

2024-04-02 20:24 UTC, nex3 commented on js-api-doc/logger/index.d.ts
> +   * @param options.dperecationType - The type of deprecation this warning is
```suggestion
   * @param options.deprecationType - The type of deprecation this warning is
```

2024-04-02 20:24 UTC, nex3 commented on js-api-doc/options.d.ts
> +   * eventually break
Nit: period

2024-04-02 20:24 UTC, nex3 commented on js-api-doc/deprecations.d.ts
> +   * Parses a version from a string.
This should probably document that it'll throw an error if the version can't be parsed.

2024-04-02 20:24 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +> stylesheet dependencies.
Copy-paste error

2024-04-02 20:24 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +#### `call-string`
I think we can get away without summaries here, since the individual specs say "emit a deprecation named ...".

2024-04-02 20:24 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +obsolete.
Probably worth mentioning that this is also implementation-dependent.

2024-04-02 20:24 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +This must be a non-negative integer.
Since the spec is describing how an implementation should _behave_, it should define what happens if the number is negative rather than just declaring that it must not be.

2024-04-02 20:24 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +Parses a string in the form "major.minor.patch" into a `Version`.
Similarly, this should define what happens if parsing fails.

2024-04-02 20:40 UTC, nex3 commented
We should also explicitly specify what happens if the host refers to a deprecation ID that the compiler doesn't recognize or vice-versa. In the former case, I think the compiler should just throw an error, because the host should generally be responsible for ensuring it's speaking a compatible protocol to the compiler. In the latter case, I think it's fine to say that the warning is treated as a non-deprecation.

2024-04-02 20:41 UTC, nex3 commented on js-api-doc/logger/index.d.ts
> +      deprecationType?: Deprecation;
We should probably type this explicitly so that `deprecationType` is set if and only if `deprecation` is true.

2024-04-03 01:54 UTC, jathak commented on js-api-doc/deprecations.d.ts
> +   * Parses a version from a string.
Done

2024-04-03 01:54 UTC, jathak commented on js-api-doc/deprecations.d.ts
> +  'user-authored': Deprecation<'user-authored', 'user'>;
I've added a test to https://github.com/sass/sass-spec/pull/1967 to ensure that Dart Sass and the embedded host don't expose any extra deprecations, which I think should be sufficient until we switch the deprecations list to a single source-of-truth (tracked in https://github.com/sass/sass/issues/3827)

2024-04-03 01:54 UTC, jathak commented on js-api-doc/logger/index.d.ts
> +   * @param options.dperecationType - The type of deprecation this warning is
Done

2024-04-03 01:54 UTC, jathak commented on js-api-doc/logger/index.d.ts
> +      deprecationType?: Deprecation;
Done. Is this the cleanest way to write this type, or is there some fancy Typescript feature to make `deprecationType` directly dependent on `deprecation`'s value?

2024-04-03 01:54 UTC, jathak commented on js-api-doc/options.d.ts
> +   * eventually break
Done

2024-04-03 01:54 UTC, jathak commented on spec/js-api/deprecations.d.ts.md
> +Parses a string in the form "major.minor.patch" into a `Version`.
Done.

2024-04-03 01:54 UTC, jathak commented on spec/js-api/deprecations.d.ts.md
> +This must be a non-negative integer.
Done (updated the constructor spec to say the compiler should throw an error)

2024-04-03 01:54 UTC, jathak commented on spec/js-api/deprecations.d.ts.md
> +obsolete.
Done

2024-04-03 01:54 UTC, jathak commented on spec/js-api/deprecations.d.ts.md
> +#### `call-string`
Removed

2024-04-03 01:54 UTC, jathak commented on spec/js-api/deprecations.d.ts.md
> +> stylesheet dependencies.
Fixed

2024-04-03 19:43 UTC, nex3 commented on js-api-doc/logger/index.d.ts
> +      deprecationType?: Deprecation;
I think this is the best option

2024-04-03 19:50 UTC, nex3 approved these changes

2024-04-03 19:50 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +#### `call-string`
You could even get rid of the headers and have this all be a single code block.

2024-04-03 19:50 UTC, nex3 commented on spec/js-api/deprecations.d.ts.md
> +The status of this deprecation.
Missing a header.

2024-04-03 21:14 UTC, merged